# Generated by Django 4.0.4 on 2022-05-31 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=64, verbose_name='Название направления')),
                ('teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Педагоги')),
            ],
            options={
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64, verbose_name='Название группы')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.direction', verbose_name='Направление')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'группу',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='PaidGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64, verbose_name='Название группы')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.direction', verbose_name='Направление')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Педагог')),
            ],
            options={
                'verbose_name': 'платную группу',
                'verbose_name_plural': 'Платные группы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=64, verbose_name='Название образовательной организации')),
            ],
            options={
                'verbose_name_plural': 'Образовательные организации',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(verbose_name='Педагог')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/photos', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('parent_name', models.CharField(max_length=96, verbose_name='ФИО Родителя')),
                ('parent_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона родителя')),
                ('address', models.CharField(max_length=96, verbose_name='Адрес проживания')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('status', models.IntegerField(choices=[(0, 'Зачислен'), (1, 'Не все документы сданы'), (2, 'Отчислен'), (3, 'На рассмотрении')], default=3, verbose_name='Статус')),
                ('social_category', models.IntegerField(choices=[(0, 'Отсутствует'), (1, 'Многодетная семья'), (2, 'Неполная семья'), (3, 'Инвалидность'), (4, 'Ограниченные возможности здоровья')], default=0, verbose_name='Социальная категория')),
                ('petition_date', models.DateField(auto_now=True, verbose_name='Дата подачи заявления')),
                ('adding_date', models.DateField(blank=True, null=True, verbose_name='Дата зачисления')),
                ('delete_date', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('adding_document', models.FileField(blank=True, upload_to='static/documents', verbose_name='Приказ зачисления')),
                ('delete_document', models.FileField(blank=True, upload_to='static/documents', verbose_name='Приказ отчисления')),
                ('delete_comment', models.CharField(default='', max_length=128, verbose_name='Причина отчисления')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Внебюджет')),
                ('paid_doc', models.FileField(blank=True, upload_to='static/documents', verbose_name='Договор внебюджет')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата зачисления внебюджет')),
                ('paid_delete_doc', models.FileField(blank=True, upload_to='static/documents', verbose_name='Приказ отчисления внебюджет')),
                ('paid_delete_date', models.DateField(blank=True, null=True, verbose_name='Дата отчисления внебюджет')),
                ('paid_delete_comment', models.CharField(default='', max_length=128, verbose_name='Причина отчисления внебюджет')),
                ('petition_doc', models.FileField(blank=True, upload_to='static/documents', verbose_name='Заявление на зачисление')),
                ('sms_agreement_doc', models.FileField(blank=True, upload_to='static/documents', verbose_name='Расписка на получение SMS сообщений')),
                ('agreement_doc', models.FileField(blank=True, upload_to='static/documents', verbose_name='Согласие на обработку персональных данных')),
                ('passport_copy_parent', models.FileField(blank=True, upload_to='static/documents', verbose_name='Копия паспорта родителя')),
                ('passport_or_birth_copy', models.FileField(blank=True, upload_to='static/documents', verbose_name='Копия паспорта/свидетельства о рождении ребёнка')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.direction', verbose_name='Направление')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Группа')),
                ('paid_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.paidgroup', verbose_name='Внебюджетная группа')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'учащийся',
                'verbose_name_plural': 'Учащиеся',
            },
        ),
    ]
